<a href="https://colab.research.google.com/github/Ishikamehra05/Big-Data-Analytics/blob/main/asg2_31_01_24_202301023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#ques1
import numpy as np
arr=np.array([1, 2, 3, 6, 4, 5])
res=np.flip(arr)
print(res)

[5 4 6 3 2 1]


In [ ]:
#ques2
import numpy as np
arr1=np.array([[1], [3, 4]])
arr2=np.array([[1, 2], [3, 4]])
compare= arr1 == arr2
arr=compare.all()
print(arr)

False


<ipython-input-5-7dfaef8e2444>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1=np.array([[1], [3, 4]])


In [ ]:
#ques3
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3,4,4,4])
print("Original array:")
print(x)
print(y)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())
print("Most frequent value in the above array:")
print(np.bincount(y).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
[1 1 1 2 3 4 2 4 3 3 4 4 4]
Most frequent value in the above array:
1
Most frequent value in the above array:
4


In [ ]:
#ques4
import numpy as np

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

sum_all_elements = gfg.sum()

sum_row_wise = gfg.sum(axis=1)

sum_column_wise = gfg.sum(axis=0)

print("i. Sum of all elements:", sum_all_elements)
print("ii. Sum of all elements row-wise:", sum_row_wise)
print("iii. Sum of all elements column-wise:", sum_column_wise)

i. Sum of all elements: 45
ii. Sum of all elements row-wise: [[14]
 [16]
 [15]]
iii. Sum of all elements column-wise: [[20  9 16]]
