<a href="https://colab.research.google.com/github/Ishikamehra05/Big-Data-Analytics/blob/main/labeval_mca1_202301023.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
#multiply the following matrices and also find covariance between matrices using
#numpy: i.p=[[1,2],[2,3]]q=[[4,5],[6,7]]
import numpy as np

p = np.array([[1, 2], [2, 3]])
q = np.array([[4, 5], [6, 7]])


product = np.dot(p, q)
print("Product of matrices:")
print(product)



covariance=np.cov(product)
print("covariance b/w matrices:")
print(covariance)


Product of the matrices:
[[16 19]
 [26 31]]
[[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]
